version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - skip-release
    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - skip-release
    groups:
      common:
        patterns:
          - "@types/*"
      lint:
        patterns:
          - "@biomejs/biome"
          - "@kibertoad/biome-config"
      testing:
        patterns:
          - "vitest"
          - "@vitest/*"
          - "memory-watchmen"
      typescript:
        patterns:
          - "typescript"
    cooldown:
      default-days: 7
